### ISSUE TITLE
不同页面item点击与长按事件进行了覆盖

### ISSUE THREAD

**Issue by imliujun** [tianzhijiexian/ExRecyclerView#3]
最新引用此控件出现这样一个问题，在fragment中有viewpage，viewpage中放入两个fragment都分别作为刷新列表，都是LinearLayoutManager样式，但点击与长按事件进行了覆盖；例：fragment1有点击1事件，长按1事件。fragment2有点击事件。出现的情况为：点击fragment1的Item触发的是fragment2中的Item点击事件；fragment2并没有注册长按事件，但实际操作会触发fragment1的长按事件并都执行其中方法。

**Comment by tianzhijiexian** [comment]
知道了您的问题，我会在下个版本中移除全局的长按，让item内部自己处理长按事件。这样就不会出现您所说的问题了，我应该会在近期更新一下

**Comment by tianzhijiexian** [comment]
我今天花了一天的时间重构了下代码，换了种实现方式。如果你想要了解具体的进度，你可以通过邮件联系到我。developer_kale@qq.com

**Comment by imliujun** [comment]
你这个项目是我在网上找遍了所有开源的二次封装RecyclerView中最简洁最实用的一个了。
别的要么太复杂，功能太臃肿，要么集成了一些乱七八糟的东西，要么效果不够好。
所以要非常感谢你们这群乐于分享、为开源做贡献的人。
已经将ExRecyclerView用在项目中了，所以等你这边更新发布到maven上后，我会用gradle更新版本。

**Comment by tianzhijiexian** [comment]
我的一般原则就是最简单实用，这回会进行代码的整理和部分的优化。希望可以满足你的需求

**Comment by tianzhijiexian** [comment]
现在已经利用了组合的思想进行了项目的重构，现在你只需要将原先的适配器传入我提供的适配器包装类就可以实现添加都和底的操作了，同时不推荐把item的点击事件用setOnItemClick做，请参考我另外的一个项目commonAdapter的实现思路。二者结合会更加简洁哦~
