### ISSUE TITLE
ExRecyclerView快速滑动到底部会触发多次onBottom方法

### ISSUE THREAD

**Issue by imliujun** [tianzhijiexian/ExRecyclerView#5]
采用GridLayoutManager特别明显（我设置的列数为2），LinearLayoutManager在快速滑动出现几率也很大

**Comment by tianzhijiexian** [comment]
这个可能和它的加载机制有关，我来看看。应该会尽快修复的，谢谢你的反馈~！

**Comment by tianzhijiexian** [comment]
我重新改了下代码，发现这个不能复现了，我希望你能参与到最新的代码的测试中。看看这个问题是否得到了解决，我的qq 460412008

**Comment by tianzhijiexian** [comment]
代码的设计原先就是如果到了底部就触发回调，如果用户在到底后不断的上滑也会触发这样的回调。如果做了loading的操作，建议加上isLoading的判断。我的建议是这个判断还是放在使用者这里去做，毕竟一个库针对的是不同的需求。
